spring.application.name=eduplatform
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# DataSource configuration
spring.datasource.url=jdbc:h2:mem:worldcuphub;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Initialization settings
spring.sql.init.mode=always
# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
server.port=8081